rsahilt/homeeleganz

- homeeleganz/documents/README.MD
- proposed tables and field in documents
> Added to proposal database - tables and proposed fields data

- homeeleganz/documents/README.MD
> Updated list of tables

- homeeleganz/documents/templates/login.html
- templates/login.html created
> login.html template created

- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/list-view.blade.php
> list-view fixed

- homeeleganz/resources/css/app.css
> css changed

- homeeleganz/documents/README.MD
- added frontend design in proposal
> added design in proposal

- homeeleganz/documents/README.MD
> proposal editing

- homeeleganz/documents/README.MD
> editing project

- homeeleganz/documents/README.MD
- proposal modified because unchanged push
> project push again

- homeeleganz/database/migrations/2023_12_05_212936_create_categories_table.php
> Installed proj dependecies and created migration for categories

- homeeleganz/resources/views/checkout.blade.php
- homeeleganz/routes/web.php
- checkout structure completed
> checkout completed

- homeeleganz/documents/README.MD
> proposal completed

- homeeleganz/resources/views/list-view.blade.php
- homeeleganz/resources/views/partials/header.blade.php
- homeeleganz/routes/web.php
- Navigation added
- Cards added
> changes in products page

- homeeleganz/documents/README.MD
> Updated server details and steps followed for server setup

- homeeleganz/documents/README.MD
- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/details.blade.php
- product details, reviews static view completed
> product details static laravel view completed

- homeeleganz/app/Models/Product.php
- homeeleganz/database/factories/ProductFactory.php
- homeeleganz/database/migrations/2023_12_06_173216_create_products_table.php
- homeeleganz/database/seeders/DatabaseSeeder.php
- homeeleganz/documents/README.MD
> minor changes fixed

- homeeleganz/database/migrations/2023_12_06_194931_create_taxes_table.php
- homeeleganz/database/seeders/DatabaseSeeder.php
- homeeleganz/database/seeders/TaxesSeeder.php
- added migrations and seeders for taxes
> Added migrations and seeders for taxes

- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/about.blade.php
- css stylings fixed in about us page
> about us css fixed

- homeeleganz/app/Models/Category.php
- homeeleganz/app/Models/Order.php
- homeeleganz/app/Models/Product.php
- homeeleganz/app/Models/User.php
> Updated database model relationships

- homeeleganz/resources/views/details.blade.php
- submit button for user review
> submit button for review

- homeeleganz/resources/views/details.blade.php
- short description retrieved
- for latest pull for group
> - short description retrieved

- homeeleganz/resources/views/details.blade.php
> auth filter on review box

- homeeleganz/resources/views/partials/header.blade.php
- changes in header/auth links
> - changes in header/auth links

- homeeleganz/app/Models/Category.php
- homeeleganz/app/Models/Product.php
- homeeleganz/vite.config.js
- updated css path for vite config
> updated css path for vite config

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/views/category.blade.php
- homeeleganz/resources/views/partials/header.blade.php
- homeeleganz/routes/web.php
- products showing by category
> filter on products with category

- homeeleganz/vite.config.js
- Edits made to include sass & css in vite config
> Edits made to include sass & css in vite config

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/app/Models/Product.php
- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/category.blade.php
- homeeleganz/resources/views/products.blade.php
> active category in products css fixed

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/views/brands.blade.php
- homeeleganz/resources/views/partials/header.blade.php
- homeeleganz/routes/web.php
> brands page

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/views/brands.blade.php
- homeeleganz/resources/views/contact.blade.php
- homeeleganz/resources/views/index.blade.php
- homeeleganz/resources/views/partials/header.blade.php
- testimonials added in index (static)
- contact page created (static)
> working on index and contact pages

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/app/Models/Message.php
- homeeleganz/database/migrations/2023_12_09_150222_create_messages_table.php
- homeeleganz/resources/views/contact.blade.php
- homeeleganz/routes/web.php
- nav fixed in contact us page
- form edited
- messages migration, Message Model and store method in controller created
- submitted data successfully reflecting in database table
> user able to send feedback from contact us page

- homeeleganz/resources/views/about.blade.php
- homeeleganz/resources/views/brands.blade.php
- homeeleganz/resources/views/cart.blade.php
- homeeleganz/resources/views/category.blade.php
- homeeleganz/resources/views/checkout.blade.php
- homeeleganz/resources/views/contact.blade.php
- homeeleganz/resources/views/details.blade.php
- homeeleganz/resources/views/home.blade.php
- homeeleganz/resources/views/index.blade.php
- homeeleganz/resources/views/products.blade.php
> cart icon added in every page

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/details.blade.php
- homeeleganz/resources/views/index.blade.php
- homeeleganz/resources/views/layouts/main.blade.php
- homeeleganz/routes/web.php
- flash message timer script added 
- review stored and dynamically displayed
> Flash timer, review storing and dynamic retrieval

- homeeleganz/resources/views/category.blade.php
- homeeleganz/resources/views/products.blade.php
- category name displayed in product card
> category name displayed in product card

- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/resources/views/admin/products/create.blade.php
- homeeleganz/resources/views/admin/products/edit.blade.php
- homeeleganz/resources/views/admin/products/index.blade.php
- homeeleganz/resources/views/layouts/app.blade.php
- homeeleganz/routes/web.php
- all products displayed
- create form added (no functionality yet)
- edit form with prepopulated data
> working on CRUD products table

- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/resources/views/admin/products/create.blade.php
- homeeleganz/routes/web.php
> completed create form for products table

- homeeleganz/app/Http/Controllers/Admin/AdminController.php
- homeeleganz/app/Http/Kernel.php
- homeeleganz/app/Http/Middleware/AdminAccess.php
- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/admin/dashboard.blade.php
- homeeleganz/resources/views/index.blade.php
- homeeleganz/resources/views/partials/header.blade.php
- homeeleganz/routes/web.php
> Admin Dashboard

- homeeleganz/app/Http/Controllers/Admin/ControllerAdmin.php
- homeeleganz/routes/web.php
- AdminController changed to ControllerAdmin
> controllers conflict fixed

- homeeleganz/app/Http/Controllers/Admin/ControllerAdmin.php
- homeeleganz/resources/views/admin/dashboard.blade.php
- messages from contact us displayed in dashboard
> messages displayed in dashboard

- homeeleganz/resources/views/details.blade.php
> details view fixed

- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/admin/dashboard.blade.php
- homeeleganz/resources/views/admin/products/create.blade.php
- homeeleganz/resources/views/admin/products/edit.blade.php
- homeeleganz/resources/views/admin/products/index.blade.php
- homeeleganz/resources/views/details.blade.php
- homeeleganz/resources/views/layouts/app.blade.php
- homeeleganz/resources/views/partials/aside.blade.php
- homeeleganz/resources/views/products.blade.php
- errors in details page fixed
> details page errors fixed

- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/resources/views/admin/products/index.blade.php
- homeeleganz/routes/web.php
- CRUD Completed for products (images file left)
> products destroy method added

- homeeleganz/app/Http/Controllers/Admin/UserController.php
- homeeleganz/resources/views/admin/users/create.blade.php
- homeeleganz/resources/views/admin/users/edit.blade.php
- homeeleganz/resources/views/admin/users/index.blade.php
- homeeleganz/resources/views/details.blade.php
- homeeleganz/routes/web.php
- working on list view and create form for users
> create users - backend

- homeeleganz/resources/views/admin/users/create.blade.php
- homeeleganz/resources/views/admin/users/index.blade.php
> working on create for users

- homeeleganz/resources/views/admin/dashboard.blade.php
- cards added in dashboard theme
> working on dashboard theme

- homeeleganz/resources/views/admin/dashboard.blade.php
- cards added in dashboard theme
> dashboard changes

- homeeleganz/app/Http/Controllers/Admin/ControllerAdmin.php
- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/resources/views/admin/dashboard.blade.php
- homeeleganz/resources/views/admin/products/index.blade.php
- multiple categories for products displayed
- paginate added in dashboard list
- count for rows in tables for dashboard data
> dashboard multiple categories displayed

- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/resources/views/details.blade.php
- edit made to admin product controller
> Edits made to admin product controller

- homeeleganz/app/Http/Controllers/Admin/ControllerAdmin.php
- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/app/Http/Controllers/Admin/ReviewController.php
- homeeleganz/app/Http/Controllers/Admin/UserController.php
- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/views/admin/dashboard.blade.php
- homeeleganz/resources/views/admin/reviews/index.blade.php
- homeeleganz/resources/views/admin/users/edit.blade.php
- homeeleganz/resources/views/partials/aside.blade.php
- Edit form for users fixed
- Review list fixed ; showing user's name and product name, before it was showing id
- slug added in dashboard to see where the user is (on which page)
- 5 latest prods and users added as content for landing admin dahsboard page
> fixing backend codes

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/views/partials/header.blade.php
- homeeleganz/resources/views/products.blade.php
- homeeleganz/routes/web.php
- created route for search
- fixed form in search
- created controller method for search in ProductController
- tested succesfully
> search working frontend

- homeeleganz/resources/views/products.blade.php
- modification in products.blade.php
> add to cart button replaces view details in list view of products

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/app/Models/Tax.php
- homeeleganz/resources/views/cart.blade.php
- in cart blade, tax displayed as per province of the user
> taxes displaying as per province

- homeeleganz/app/Http/Controllers/Admin/UserController.php
- homeeleganz/app/Http/Controllers/HomeController.php
- homeeleganz/resources/views/home-edit.blade.php
- homeeleganz/resources/views/home.blade.php
- homeeleganz/routes/web.php
> user profile edit completed

- homeeleganz/app/Http/Controllers/Admin/UserController.php
- homeeleganz/resources/views/home-edit.blade.php
- homeeleganz/resources/views/home.blade.php
- homeeleganz/resources/views/user-reviews.blade.php
- homeeleganz/routes/web.php
> reviews added in profile

- homeeleganz/app/Http/Controllers/Admin/ControllerAdmin.php
- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/app/Http/Controllers/Admin/TaxController.php
- homeeleganz/app/Models/Tax.php
- homeeleganz/database/factories/ProductFactory.php
- homeeleganz/database/seeders/ProductsSeeder.php
- homeeleganz/resources/views/details.blade.php
- edits made in admin and user views
- seeder
> Edits made in Admin and User views.Added seeder to db.

- homeeleganz/app/Http/Controllers/ProductController.php
- homeeleganz/resources/views/cart.blade.php
- homeeleganz/resources/views/checkout.blade.php
- checkout blade getting data from cart session
> checkout session successfull

- homeeleganz/app/Http/Controllers/Admin/ProductController.php
- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/admin/products/create.blade.php
- homeeleganz/resources/views/admin/products/edit.blade.php
- homeeleganz/resources/views/cart.blade.php
- homeeleganz/resources/views/details.blade.php
- homeeleganz/resources/views/products.blade.php
- image displaying in cart, products list, details view, adding new image successfully
- edit form image problem
> working on image upload and edit

- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/category.blade.php
- images dynamically displaying in categories under products
- working on cart styling
> images displayed in categories list

- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/index.blade.php
- homeeleganz/resources/views/layouts/main.blade.php
- homeeleganz/resources/views/partials/footer.blade.php
- homeeleganz/resources/views/partials/header.blade.php
> styled, header, nav and search

- homeeleganz/resources/views/partials/header.blade.php
> hamburger created. work in progress with responsiveness

- homeeleganz/resources/views/partials/header.blade.php
> changes in header

- homeeleganz/app/Http/Controllers/ApiController.php
- homeeleganz/composer.json
- homeeleganz/composer.lock
- homeeleganz/resources/views/cart.blade.php
- homeeleganz/resources/views/checkout.blade.php
- homeeleganz/resources/views/invoice.blade.php
- homeeleganz/routes/web.php
- api running on payment validation
- problem when there is error message
> Api running for good validation

- homeeleganz/app/Http/Controllers/Admin/UserController.php
- homeeleganz/resources/views/admin/users/create.blade.php
- homeeleganz/resources/views/admin/users/edit.blade.php
- added street and country in users CRUD
> updated Users CRUD

- homeeleganz/resources/views/partials/header.blade.php
> hamburger menu working properly

- homeeleganz/app/Http/Controllers/Admin/UserController.php
- homeeleganz/resources/views/home-edit.blade.php
- homeeleganz/resources/views/home.blade.php
- User profile edit form updated
> User profile edit form updated

- homeeleganz/app/Http/Controllers/ApiController.php
- homeeleganz/resources/views/cart.blade.php
- homeeleganz/routes/web.php
- conflict in route and apicontroller fixed
- payment validation working correctly
- coded for inserting data into orders and line_items table
> payment validation and inserting into 

- homeeleganz/app/Http/Controllers/ApiController.php
- navraj helped with inserting into orders and line_items
> inserting into orders and line_items table

- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/admin/dashboard.blade.php
- homeeleganz/resources/views/category.blade.php
- homeeleganz/resources/views/details.blade.php
- homeeleganz/resources/views/home-edit.blade.php
- homeeleganz/resources/views/layouts/dashboardheader.blade.php
- homeeleganz/resources/views/products.blade.php
- homeeleganz/resources/views/user-reviews.blade.php
-categories slug
-dashboard header fixed
-fixed details view
-fixed user reviews view
-fixed edit info by user view
> worked on frontend contents

- homeeleganz/app/Http/Controllers/ApiController.php
- homeeleganz/database/migrations/2023_12_07_185404_create_transactions_table.php
- homeeleganz/resources/css/app.css
- homeeleganz/resources/views/cart.blade.php
- homeeleganz/resources/views/checkout.blade.php
- homeeleganz/resources/views/partials/header.blade.php
- data inserted into tables even if invalid as status 0
- if valid, status of order is updated to 1
> line_items, orders and transaction working
